### PR TITLE
Change case of Config/watchtower.php to Config/Watchtower.php fixing …

### PR DESCRIPTION
**Pull request by antoniopaisfernandes**
…issue with 'php artisan clear-compiled'

It throws an error on case-sensitive OSs in method boot of WatchtowerServiceProvider.

### CODE REVIEW

**Comment by landjea** [comment]
Hi @antoniopaisfernandes . I use this package in both ubuntu and CentOS as well and don't have any issue like this. I also modeled it after all the other config file packages I have found that do the same thing. Are you sure this is causing your issue?

**Comment by landjea** [comment]
Ugh, nevermind. I see why it is working on my other boxes. I think a better fix would be to correct the casing in the serviceprovider. I will do that now. Sorry @antoniopaisfernandes .

**Comment by landjea** [comment]
Changed case in ServiceProvider. If this doesn't work for you now, let me know.

Thanks!

**Comment by antoniopaisfernandes** [comment]
I see you changed it in another branch other than master. Will it be merged there? What's that branch about? Just layout changes?

Would you consider adding a feature to allow route prefixes in Watchtower?
Something like adding to the config a setting (eg: routes_prefix = '/admin/') and that would prepend the routes. Being something like '/admin/watchtower/'...

**Comment by landjea** [comment]
The other branch is for the navigation feature I am testing. I use "watchtower" for all my stuff and wanted an easy way to add more options to the top navigation bar. (and I like config files :) )

Something like this image _(notice the extra two options on the nav bar of a fist and a dollar sign)_:
 

As soon as my testing proves out, I will merge it with master.

A prefix on routes sounds sensible. I will hop on it asap. Probably tonight.

**Comment by antoniopaisfernandes** [comment]
Great! :) Thanks

**Comment by landjea** [comment]
Added route_prefix.. Hope it works out right.

**Comment by antoniopaisfernandes** [comment]
Hi,

It works nicely.

Thanks

**Pull request closed without merging**
